# Generated by Django 4.2 on 2023-08-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_total_correct_responses_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="total_time_spent",
        ),
    ]
