# Generated by Django 4.2 on 2023-08-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_total_time_spent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="total_correct_responses",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="total_incorrect_responses",
        ),
    ]
